version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive ./build s3://dframe-test/
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
  